// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GDGSids
{
        public const string achievement_dodged_5_hazards = "CgkIzpi-qqMDEAIQAQ"; // <GPGSID>
        public const string event_angled_game = "CgkIzpi-qqMDEAIQCA"; // <GPGSID>
        public const string achievement_dodged_25_hazards = "CgkIzpi-qqMDEAIQAw"; // <GPGSID>
        public const string event_normal_game = "CgkIzpi-qqMDEAIQBw"; // <GPGSID>
        public const string leaderboard_normal = "CgkIzpi-qqMDEAIQBg"; // <GPGSID>
        public const string achievement_dodged_100_hazards = "CgkIzpi-qqMDEAIQBQ"; // <GPGSID>
        public const string achievement_dodged_50_hazards = "CgkIzpi-qqMDEAIQBA"; // <GPGSID>
        public const string achievement_dodged_10_hazards = "CgkIzpi-qqMDEAIQAg"; // <GPGSID>
        public const string leaderboard_double = "CgkIzpi-qqMDEAIQCw"; // <GPGSID>
        public const string leaderboard_angled = "CgkIzpi-qqMDEAIQCg"; // <GPGSID>
        public const string event_double_game = "CgkIzpi-qqMDEAIQCQ"; // <GPGSID>

}

